name: publish_all.yml
on: workflow_dispatch

jobs:
  publish:
    name: Publish All Versions
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

